# Generated by Django 3.0.3 on 2020-04-13 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carlosApp', '0003_auto_20200413_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('airline_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('airline_name', models.CharField(max_length=150)),
                ('airline_actif', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('airport_name', models.CharField(max_length=150)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('timezone1', models.FloatField()),
                ('timezone2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('country_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('plane_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('plane_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('routes_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('airline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carlosApp.Airline')),
                ('airport_id_dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carlosApp.Airport')),
                ('airport_id_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_id_source', to='carlosApp.Airport')),
                ('plane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carlosApp.Plane')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('city_name', models.CharField(max_length=50)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carlosApp.Country')),
            ],
        ),
        migrations.AddField(
            model_name='airport',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carlosApp.City'),
        ),
        migrations.AddField(
            model_name='airline',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carlosApp.Country'),
        ),
    ]
